export const countries: { countryName: string; countryCode: string; }[] = [
    { countryName: 'Afganistan', countryCode: 'AF' },
    { countryName: 'Almanya', countryCode: 'DE' },
    { countryName: 'Amerika Birleşik Devletleri', countryCode: 'US' },
    { countryName: 'Andorra', countryCode: 'countryName' },
    { countryName: 'Angola', countryCode: 'AO' },
    { countryName: 'Antigua ve Barbuda', countryCode: 'AG' },
    { countryName: 'Arjantin', countryCode: 'AR' },
    { countryName: 'Arnavutluk', countryCode: 'AL' },
    { countryName: 'Avustralya', countryCode: 'AU' },
    { countryName: 'Avusturya', countryCode: 'AT' },
    { countryName: 'Azerbaycan', countryCode: 'AZ' },
    { countryName: 'Bahamalar', countryCode: 'BS' },
    { countryName: 'Bahreyn', countryCode: 'BH' },
    { countryName: 'Bangladeş', countryCode: 'BD' },
    { countryName: 'Barbados', countryCode: 'BB' },
    { countryName: 'Batı Sahara', countryCode: 'EH' },
    { countryName: 'Belarus', countryCode: 'BY' },
    { countryName: 'Belçika', countryCode: 'BE' },
    { countryName: 'Belize', countryCode: 'BZ' },
    { countryName: 'Benin', countryCode: 'BJ' },
    { countryName: 'Bermuda', countryCode: 'BM' },
    { countryName: 'Birleşik Arap Emirlikleri', countryCode: 'AE' },
    { countryName: 'Birleşik Krallık', countryCode: 'GB' },
    { countryName: 'Bolivya', countryCode: 'BO' },
    { countryName: 'Bosna-Hersek', countryCode: 'BA' },
    { countryName: 'Botsvana', countryCode: 'BW' },
    { countryName: 'Brezilya', countryCode: 'BR' },
    { countryName: 'Brunei', countryCode: 'BN' },
    { countryName: 'Bulgaristan', countryCode: 'BG' },
    { countryName: 'Burkina Faso', countryCode: 'BF' },
    { countryName: 'Burundi', countryCode: 'BI' },
    { countryName: 'Cape Verde', countryCode: 'CV' },
    { countryName: 'Cebelitarık', countryCode: 'GI' },
    { countryName: 'Cezayir', countryCode: 'DZ' },
    { countryName: 'Cibuti', countryCode: 'DJ' },
    { countryName: 'Çad', countryCode: 'TD' },
    { countryName: 'Çek Cumhuriyeti', countryCode: 'CZ' },
    { countryName: 'Çin', countryCode: 'CN' },
    { countryName: 'Danimarka', countryCode: 'DK' },
    { countryName: 'Dominika', countryCode: 'DM' },
    { countryName: 'Doğu Timor', countryCode: 'TL' },
    { countryName: 'Dominik Cumhuriyeti', countryCode: 'DO' },
    { countryName: 'Ekvador', countryCode: 'EC' },
    { countryName: 'El Salvador', countryCode: 'SV' },
    { countryName: 'Endonezya', countryCode: 'ID' },
    { countryName: 'Eritre', countryCode: 'ER' },
    { countryName: 'Ermenistan', countryCode: 'AM' },
    { countryName: 'Estonya', countryCode: 'EE' },
    { countryName: 'Esvatini', countryCode: 'SZ' },
    { countryName: 'Etiyopya', countryCode: 'ET' },
    { countryName: 'Fas', countryCode: 'MA' },
    { countryName: 'Fiji', countryCode: 'FJ' },
    { countryName: 'Fildişi Sahili', countryCode: 'CI' },
    { countryName: 'Filipinler', countryCode: 'PH' },
    { countryName: 'Filistin Bölgesi', countryCode: 'PS' },
    { countryName: 'Finlandiya', countryCode: 'FI' },
    { countryName: 'Fransa', countryCode: 'FR' },
    { countryName: 'Gabon', countryCode: 'GA' },
    { countryName: 'Gambiya', countryCode: 'GM' },
    { countryName: 'Gana', countryCode: 'GH' },
    { countryName: 'Gine', countryCode: 'GN' },
    { countryName: 'Gine-Bissau', countryCode: 'GW' },
    { countryName: 'Grenada', countryCode: 'GD' },
    { countryName: 'Grönland', countryCode: 'GL' },
    { countryName: 'Guam', countryCode: 'GU' },
    { countryName: 'Guatemala', countryCode: 'GT' },
    { countryName: 'Guyana', countryCode: 'GY' },
    { countryName: 'Güney Afrika', countryCode: 'ZA' },
    { countryName: 'Güney Kore', countryCode: 'KR' },
    { countryName: 'Güney Sudan', countryCode: 'SS' },
    { countryName: 'Gürcistan', countryCode: 'GE' },
    { countryName: 'Haiti', countryCode: 'HT' },
    { countryName: 'Hırvatistan', countryCode: 'HR' },
    { countryName: 'Hindistan', countryCode: 'IN' },
    { countryName: 'Hollanda', countryCode: 'NL' },
    { countryName: 'Honduras', countryCode: 'HN' },
    { countryName: 'Hong Kong', countryCode: 'HK' },
    { countryName: 'Irak', countryCode: 'IQ' },
    { countryName: 'İngiltere', countryCode: 'GB' },
    { countryName: 'İran', countryCode: 'IR' },
    { countryName: 'İrlanda', countryCode: 'IE' },
    { countryName: 'İspanya', countryCode: 'ES' },
    { countryName: 'İsrail', countryCode: 'IL' },
    { countryName: 'İsveç', countryCode: 'SE' },
    { countryName: 'İsviçre', countryCode: 'CH' },
    { countryName: 'İtalya', countryCode: 'IT' },
    { countryName: 'İzlanda', countryCode: 'IS' },
    { countryName: 'Jamaika', countryCode: 'JM' },
    { countryName: 'Japonya', countryCode: 'JP' },
    { countryName: 'Kamboçya', countryCode: 'KH' },
    { countryName: 'Kamerun', countryCode: 'CM' },
    { countryName: 'Kanada', countryCode: 'CA' },
    { countryName: 'Karadağ', countryCode: 'ME' },
    { countryName: 'Katar', countryCode: 'QA' },
    { countryName: 'Kazakistan', countryCode: 'KZ' },
    { countryName: 'Kenya', countryCode: 'KE' },
    { countryName: 'Kıbrıs', countryCode: 'CY' },
    { countryName: 'Kırgızistan', countryCode: 'KG' },
    { countryName: 'Kiribati', countryCode: 'KI' },
    { countryName: 'Kolombiya', countryCode: 'CO' },
    { countryName: 'Komorlar', countryCode: 'KM' },
    { countryName: 'Kongo', countryCode: 'CG' },
    { countryName: 'Kongo Demokratik Cumhuriyeti', countryCode: 'CD' },
    { countryName: 'Kosta Rika', countryCode: 'CR' },
    { countryName: 'Kuveyt', countryCode: 'KW' },
    { countryName: 'Kuzey Kore', countryCode: 'KP' },
    { countryName: 'Kuzey Makedonya', countryCode: 'MK' },
    { countryName: 'Küba', countryCode: 'CU' },
    { countryName: 'Laos', countryCode: 'LA' },
    { countryName: 'Lesotho', countryCode: 'LS' },
    { countryName: 'Letonya', countryCode: 'LV' },
    { countryName: 'Liberya', countryCode: 'LR' },
    { countryName: 'Libya', countryCode: 'LY' },
    { countryName: 'Liechtenstein', countryCode: 'LI' },
    { countryName: 'Litvanya', countryCode: 'LT' },
    { countryName: 'Lübnan', countryCode: 'LB' },
    { countryName: 'Lüksemburg', countryCode: 'LU' },
    { countryName: 'Macaristan', countryCode: 'HU' },
    { countryName: 'Madagaskar', countryCode: 'MG' },
    { countryName: 'Makedonya', countryCode: 'MK' },
    { countryName: 'Malavi', countryCode: 'MW' },
    { countryName: 'Maldivler', countryCode: 'MV' },
    { countryName: 'Malezya', countryCode: 'MY' },
    { countryName: 'Mali', countryCode: 'ML' },
    { countryName: 'Malta', countryCode: 'MT' },
    { countryName: 'Marshall Adaları', countryCode: 'MH' },
    { countryName: 'Mauritius', countryCode: 'MU' },
    { countryName: 'Meksika', countryCode: 'MX' },
    { countryName: 'Mikronezya', countryCode: 'FM' },
    { countryName: 'Moldova', countryCode: 'MD' },
    { countryName: 'Monako', countryCode: 'MC' },
    { countryName: 'Mongolia', countryCode: 'MN' },
    { countryName: 'Montenegro', countryCode: 'ME' },
    { countryName: 'Moritanya', countryCode: 'MR' },
    { countryName: 'Morocco', countryCode: 'MA' },
    { countryName: 'Mozambik', countryCode: 'MZ' },
    { countryName: 'Myanmar', countryCode: 'MM' },
    { countryName: 'Namibia', countryCode: 'NA' },
    { countryName: 'Nauru', countryCode: 'NR' },
    { countryName: 'Nepal', countryCode: 'NP' },
    { countryName: 'Netherlands Antilles', countryCode: 'AN' },
    { countryName: 'Nijer', countryCode: 'NE' },
    { countryName: 'Nijerya', countryCode: 'NG' },
    { countryName: 'Nikaragua', countryCode: 'NI' },
    { countryName: 'Niue', countryCode: 'NU' },
    { countryName: 'Norveç', countryCode: 'NO' },
    { countryName: 'Orta Afrika Cumhuriyeti', countryCode: 'CF' },
    { countryName: 'Özbekistan', countryCode: 'UZ' },
    { countryName: 'Pakistan', countryCode: 'PK' },
    { countryName: 'Palau', countryCode: 'PW' },
    { countryName: 'Panama', countryCode: 'PA' },
    { countryName: 'Papua Yeni Gine', countryCode: 'PG' },
    { countryName: 'Paraguay', countryCode: 'PY' },
    { countryName: 'Peru', countryCode: 'PE' },
    { countryName: 'Polonya', countryCode: 'PL' },
    { countryName: 'Portekiz', countryCode: 'PT' },
    { countryName: 'Romanya', countryCode: 'RO' },
    { countryName: 'Ruanda', countryCode: 'RW' },
    { countryName: 'Rusya', countryCode: 'RU' },
    { countryName: 'Saint Kitts ve Nevis', countryCode: 'KN' },
    { countryName: 'Saint Lucia', countryCode: 'LC' },
    { countryName: 'Saint Vincent ve Grenadinler', countryCode: 'VC' },
    { countryName: 'Samoa', countryCode: 'WS' },
    { countryName: 'San Marino', countryCode: 'SM' },
    { countryName: 'Sao Tome ve Principe', countryCode: 'ST' },
    { countryName: 'Senegal', countryCode: 'SN' },
    { countryName: 'Seyşeller', countryCode: 'SC' },
    { countryName: 'Sırbistan', countryCode: 'RS' },
    { countryName: 'Sierra Leone', countryCode: 'SL' },
    { countryName: 'Singapur', countryCode: 'SG' },
    { countryName: 'Slovakya', countryCode: 'SK' },
    { countryName: 'Slovenya', countryCode: 'SI' },
    { countryName: 'Solomon Adaları', countryCode: 'SB' },
    { countryName: 'Somali', countryCode: 'SO' },
    { countryName: 'Sri Lanka', countryCode: 'LK' },
    { countryName: 'Sudan', countryCode: 'SD' },
    { countryName: 'Surinam', countryCode: 'SR' },
    { countryName: 'Suriye', countryCode: 'SY' },
    { countryName: 'Suudi Arabistan', countryCode: 'SA' },
    { countryName: 'Svaziland', countryCode: 'SZ' },
    { countryName: 'Tacikistan', countryCode: 'TJ' },
    { countryName: 'Tanzanya', countryCode: 'TZ' },
    { countryName: 'Tayland', countryCode: 'TH' },
    { countryName: 'Tayvan', countryCode: 'TW' },
    { countryName: 'Togo', countryCode: 'TG' },
    { countryName: 'Tonga', countryCode: 'TO' },
    { countryName: 'Trinidad ve Tobago', countryCode: 'TT' },
    { countryName: 'Tunus', countryCode: 'TN' },
    { countryName: 'Turks ve Caicos Adaları', countryCode: 'TC' },
    { countryName: 'Tuvalu', countryCode: 'TV' },
    { countryName: 'Türkiye', countryCode: 'TR' },
    { countryName: 'Türkmenistan', countryCode: 'TM' },
    { countryName: 'Uganda', countryCode: 'UG' },
    { countryName: 'Ukrayna', countryCode: 'UA' },
    { countryName: 'Umman', countryCode: 'OM' },
    { countryName: 'Uruguay', countryCode: 'UY' },
    { countryName: 'Ürdün', countryCode: 'JO' },
    { countryName: 'Vanuatu', countryCode: 'VU' },
    { countryName: 'Venezuela', countryCode: 'VE' },
    { countryName: 'Vietnam', countryCode: 'VN' },
    { countryName: 'Yemen', countryCode: 'YE' },
    { countryName: 'Yeni Zelanda', countryCode: 'NZ' },
    { countryName: 'Yeşil Burun Adaları', countryCode: 'CV' },
    { countryName: 'Yunanistan', countryCode: 'GR' },
    { countryName: 'Zambiya', countryCode: 'ZM' },
    { countryName: 'Zimbabve', countryCode: 'ZW' }
];
